### ISSUE TITLE
Split up docusaurus.config.js

### ISSUE THREAD

**Issue by SohamG** [acm-uic/acm-uic.github.io#89]
Split up the json objects for Navbar and Footer into separate json/js files and reference them in docusaurus.config.js instead of having multiple levels of indentation. Thoughts?

**Comment by bmiddha** [comment]
The config is fine as it. It's not large enough to justify splitting it up. It will only make config changes more complex.

**Comment by SohamG** [comment]
Cool, thanks for the review.
