### ISSUE TITLE
💅 Update infima theme css variables

### ISSUE THREAD

**Issue by bmiddha** [acm-uic/acm-uic.github.io#99]
Theme colors are configured in custom.css
https://github.com/acm-uic/acm-uic.github.io/blob/6632298818eb48fbe5a4b0f7ad6fbfe2cd6c2828/src/css/custom.css#L1-L11

We currently the primary colors set to red. We should also update the other color variables.

The current config has some weird styling that result in a pretty bad color contrast in some situations.
Example (danger styling on light theme).
![image](https://user-images.githubusercontent.com/5100938/135773638-988ec100-8ff7-4f2f-8492-707e75aa1f5c.png)

**Comment by Masacaai** [comment]
I feel like the use of a strong red gives too much contrast and it's a bit too hard on the eyes. Maybe a lighter shade of red would work better? It might also solve the contrast issue you have with danger styling.

If you think this would work, I'll go ahead and open up a PR that uses a different shade of red.

**Comment by bmiddha** [comment]
That button is just one instance where the contrast is bad. Ideally, we want to have our own color scheme that works well on both light and dark mode.

Once we decide on the colors we want for the theme (primary, secondary, success, info, warning, danger), we can generate the shades of each color by varying the saturation, and lightless with the same hue (HSL). There's a utility mentioned in the [Docusaurus documentation](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima): [Colorbox](https://colorbox.io/)

[Infima colors](https://infima.dev/docs/utilities/colors/)

We should probably ask some designers to weigh in.
